### ISSUE TITLE
[BUG] OAuth redirects to our Callback URL and gives and Error message

### ISSUE THREAD

**Issue by ajtran303** [Shelf-Share-BEE-Mod3/shelf-share-rails#11]
**Describe the bug**

We got redirected by Goodreads to  `https://localhost:3000/callback?oauth_token=N4GLZU6MuIrggiG70fi9g&authorize=1` and get this message from the browser

```
This site can’t provide a secure connection
localhost sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

And this is the message in the terminal
```
2020-09-10 15:46:11 -0600: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
```

**To Reproduce**
1. Go to root path
2. Click on the link to log in
3. Authorize, if needed
4. Get the error message

**Expected behavior**
it should give us a routing error instead

**Screenshots**

<img width="1440" alt="Screen Shot 2020-09-10 at 3 49 50 PM" src="https://user-images.githubusercontent.com/31839316/92812857-4efebb80-f37d-11ea-8e90-89c67104d3f2.png">

**Comment by Strompy** [comment]
Fixed. Make sure goodreads callback is http, not https, for localhost
